name: Build LaTeX Document and Update README

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: documentation.tex

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Convert LaTeX to README.md
        run: |
          pandoc documentation.tex -o README.md --mathjax

      - name: Commit and Push PDF and README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-compile LaTeX to PDF and README [skip ci]"
          file_pattern: "documentation.pdf README.md"